"""add_fallback_config_unique

Revision ID: 51b6b39a9bfb
Revises: e1bca4393e2b
Create Date: 2026-06-26 23:49:00.731279
"""
from collections.abc import Sequence

revision: str = '51b6b39a9bfb'
down_revision: str | None = 'e1bca4393e2b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
