"""initial_schema

Revision ID: e1bca4393e2b
Revises:
Create Date: 2026-06-26 18:38:57.571247
"""
# ruff: noqa: E501
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e1bca4393e2b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('iv', sa.Text(), nullable=False),
    sa.Column('auth_tag', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hourly_agg',
    sa.Column('hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('total_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('avg_latency_ms', sa.Double(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('hour', 'type', 'platform', 'model_id', 'id')
    )
    op.create_table('models',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('intelligence_rank', sa.Integer(), nullable=False),
    sa.Column('speed_rank', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=50), nullable=False),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('rpd_limit', sa.Integer(), nullable=True),
    sa.Column('tpm_limit', sa.Integer(), nullable=True),
    sa.Column('tpd_limit', sa.Integer(), nullable=True),
    sa.Column('monthly_token_budget', sa.String(length=100), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_image_gen', sa.Boolean(), nullable=False),
    sa.Column('supports_audio_stt', sa.Boolean(), nullable=False),
    sa.Column('supports_audio_tts', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'model_id', name='uq_models_platform_model')
    )
    op.create_table('provisioning_log',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limit_cooldowns',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('expires_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('platform', 'model_id', 'key_id')
    )
    op.create_table('rate_limit_usage',
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('created_at_ms', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', 'id')
    )
    op.create_table('fallback_config',
    sa.Column('model_db_id', sa.Uuid(), nullable=False),
    sa.Column('pool', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_db_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('key_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('fallback_config')
    op.drop_table('settings')
    op.drop_table('rate_limit_usage')
    op.drop_table('rate_limit_cooldowns')
    op.drop_table('provisioning_log')
    op.drop_table('models')
    op.drop_table('hourly_agg')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
